image: debian:buster-slim

stages:
 - deploy
 - publish

# Common steps required for each type of build
.setup: &setup |
  set -x
  set -e
  apt-get update
  apt-get install -y curl git hugo locales make mawk python3 sassc unzip
  grep '^en_US.UTF-8 UTF-8' /etc/locale.gen || echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
  locale-gen
  export LC_ALL=en_US.UTF-8

# test deploy to GitLab Pages
pages:
  stage: deploy
  artifacts:
    paths:
      - public
    expire_in: 1w
    when: always
  script:
    - *setup
    # This is where GitLab pages will deploy to by default (e.g. "https://guardianproject.gitlab.io/info")
    # so we need to make sure that the Hugo configuration understands this.
    - 'echo "baseURL: \"https://${CI_PROJECT_NAMESPACE,,}.gitlab.io/$CI_PROJECT_NAME\"" > userconfig.yaml'
    - 'echo "Additional Hugo config used for CI:" && cat userconfig.yaml'
    - hugo env
    - make

guardianproject.info:
  stage: publish
  only:
    - master@guardianproject/info
  artifacts:
    paths:
      - public
    expire_in: 1d
  script:
    - test -z "$SSH_PRIVATE_KEY" && exit 1
    - *setup
    - 'echo "baseurl: \"https://guardianproject.info\"" > userconfig.yaml'
    - echo "Additional Hugo config used for CI:"
    - cat userconfig.yaml
    - hugo env
    - make
    - apt-get install -qy openssh-client rsync
    - mkdir -p ~/.ssh
    - chmod 0700 ~/.ssh
    - cat known_hosts >> ~/.ssh/known_hosts
    - chmod 0644 ~/.ssh/known_hosts
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - chmod -R a+rX,go-w public/
    - rsync -axv --delete public/ gpbuilds@guardianproject.info:/var/www/news/
