baseURL: "http://localhost:1313"
languageCode: "en-US"
title: "Guardian Project"

DefaultContentLanguage: "en"
Paginate: 20 # this is set low for demonstrating with dummy content. Set to a higher number
pluralizeListTitles: false
enableRobotsTXT: true

permalinks:
  blog: /:year/:month/:day/:title/

frontmatter:
  date: ["date", ":filename", ":git", ":default"]
  lastmod: ["lastmod", ":fileModTime", ":git", ":default"]

# ensure this stuff is all disabled, key bits have also been deleted
googleAnalytics: ""

sitemap:
  changefreq: "monthly"
  priority: 0.5
  filename: "sitemap.xml"

menu:
  main:
  - name: "Our Apps"
    identifier: "apps"
    url: "/apps/"
    weight: 1

  - name: "Our Code"
    identifier: "code"
    url: "/code/"
    weight: 1

  - name: "Research Archive"
    identifier: "archive"
    url: /archive/
    weight: 1

  - name: "Contact Us"
    identifier: "contact"
    weight: 100

  - name: "Toot @guardianproject@librem.one"
    url: "https://social.librem.one/@guardianproject"
    parent: "contact"

  - name: "Tweet @guardianproject"
    url: "https://twitter.com/guardianproject"
    parent: "contact"

Params:
  since: 2009
  logo: GP_Logo_hires.png
  rss: true
  favicon: ""
  description: "People, Apps and Code You Can Trust"
  mastodon: "https://social.librem.one/@guardianproject"
  twitter: "https://twitter.com/guardianproject"
  github: "https://github.com/guardianproject/"
  gitlab: "https://gitlab.com/guardianproject/"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class: "bg-black"
  # featured_image: "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number: 2
  mainSections: ["posts"]

# disable all the external Javascript, etc services from theme
  selfHosted: true
  useHLJS: false
