baseURL = "http://localhost:1313/info"
languageCode = "en-US"
title = "Guardian Project"
theme = "guardianproject"

DefaultContentLanguage = "en"
Paginate = 20 # this is set low for demonstrating with dummy content. Set to a higher number
pluralizeListTitles = false
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[menu]
  [[menu.main]]
    name = "Our Apps"
    identifier = "apps"
    url = "/apps/"
    weight = 1

  [[menu.main]]
    name = "Our Code"
    identifier = "code"
    url = "/code/"
    weight = 1
  [[menu.main]]
    name = "Development News"
    url = "/categories/development/"
    parent = "code"
    weight = -2
  [[menu.main]]
    name = "GitHub: Our Source Code"
    url = "https://github.com/guardianproject"
    parent = "code"
    weight = -1

  [[menu.main]]
    name = "Our Research"
    identifier = "research"
    weight = 1
  [[menu.main]]
    name = "Open Secure Telephony"
    url = "https://guardianproject.info/wiki/OSTN"
    parent = "research"

  [[menu.main]]
    name = "Contact Us"
    identifier = "contact"
    weight = 100
  [[menu.main]]
    name = "Tweet @guardianproject"
    url = "https://twitter.com/guardianproject"
    parent = "contact"

[params]
  favicon = ""
  description = "People, Apps and Code You Can Trust"
  facebook = ""
  twitter = "https://twitter.com/guardianproject"
  instagram = ""
  youtube = ""
  github = "https://github.com/guardianproject/"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  # featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2
  mainSections = ["posts"]
