baseURL: "http://localhost:1313"
languageCode: "en-US"
title: "Guardian Project"
theme: "guardianproject"

DefaultContentLanguage: "en"
Paginate: 20 # this is set low for demonstrating with dummy content. Set to a higher number
pluralizeListTitles: false
enableRobotsTXT: true

# ensure this stuff is all disabled, key bits have also been deleted
googleAnalytics: ""


sitemap:
  changefreq: "monthly"
  priority: 0.5
  filename: "sitemap.xml"

menu:
  main:
  - name: "Our Apps"
    identifier: "apps"
    url: "/apps/"
    weight: 1

  - name: "Our Code"
    identifier: "code"
    url: "/code/"
    weight: 1
  - name: "Development News"
    url: "/categories/development/"
    parent: "code"
    weight: -2
  - name: "GitHub: Our Source Code"
    url: "https://github.com/guardianproject"
    parent: "code"
    weight: -1

  - name: "Our Research"
    identifier: "research"
    weight: 1
  - name: "Open Secure Telephony"
    url: "https://guardianproject.info/wiki/OSTN"
    parent: "research"

  - name: "Contact Us"
    identifier: "contact"
    weight: 100
  - name: "Tweet @guardianproject"
    url: "https://twitter.com/guardianproject"
    parent: "contact"

Params:
  logo: GP_Logo_hires.png
  rss: true
  favicon: ""
  description: "People, Apps and Code You Can Trust"
  twitter: "https://twitter.com/guardianproject"
  github: "https://github.com/guardianproject/"
  gitlab: "https://gitlab.com/guardianproject/"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class: "bg-black"
  # featured_image: "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number: 2
  mainSections: ["posts"]

# disable all the external Javascript, etc services from theme
  selfHosted: true
  useHLJS: false
  gcse: false
