baseURL = "http://localhost:1313/info"
languageCode = "en-us"
title = "Guardian Project"
theme = "beautifulhugo"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 20 # this is set low for demonstrating with dummy content. Set to a higher number
pluralizeListTitles = false
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "People, Apps and Code You Can Trust"
  facebook = ""
  twitter = "https://twitter.com/guardianproject"
  instagram = ""
  youtube = ""
  github = "https://github.com/guardianproject/"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  # featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2
  mainSections = ["posts"]
